source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target 'CompanyProject' do
    
    # Objective-C
    
    pod 'AFNetworking'
    pod 'Bugly'
    pod 'TYAttributedLabel'
    pod 'TZImagePickerController'
    pod 'SECoreTextView'
    pod 'SDCycleScrollView'
    pod 'SDWebImage'
    pod 'MJExtension'
    pod 'MJRefresh'
    
    pod 'DACircularProgress'
    pod 'MBProgressHUD'
    pod 'MWPhotoBrowser'
    
    pod 'UMengAnalytics-NO-IDFA'
    pod 'MOBFoundation'
    pod 'ShareSDK3'
    pod 'ShareSDK3/ShareSDKUI'
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    pod 'ShareSDK3/ShareSDKPlatforms/Evernote'
    pod 'ShareSDK3/ShareSDKConfigurationFile'
    pod 'ShareSDK3/ShareSDKExtension'
    
    # Swift
    
    pod 'Alamofire'
    pod 'AlamofireNetworkActivityIndicator'
    pod 'BXProgressHUD'
    pod 'BFKit-Swift'
    pod 'CryptoSwift'
    pod 'DGElasticPullToRefresh'
    pod 'Kingfisher'
    
    pod 'SwiftRecord'
    pod 'SwiftDate'
    pod 'SnapKit'
    pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
    
end
